baseURL = "https://thegreatwhiteshark.github.io/"
# baseURL = "/home/phil/git/thegreatwhiteshark.github.io/public"
languageCode = "en-us"
title = "theGreatWhiteShark"
theme = "osprey"
publishDir = "public"

[Params]
	tagline = "theGreatWhiteShark"
	author = "Philipp Müller"
	description = "A root blog for all my different blogs, interests, and projects"
	github = "theGreatWhiteShark"
	logoBig = "/images/text-big.png" 
	logoSmall = "/images/text-small.png"
	email = "thetruephil@googlemail.com"
	hightlightJs = true
	credit = true
	customCSS = false

[[menu.main]]
	name = "Blogs"
	url = "/#blogs"
	weight = 1
[[menu.main]]
	name = "Projects"
	url = "/#projects"
	weight = 2
[[menu.main]]
	name = "About"
	url = "/#about"
	weight = 3